In [1]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [2]:
import tensorflow as tf
from tensorflow import keras

C:\Users\aboubakiri.diaw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\aboubakiri.diaw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\aboubakiri.diaw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\aboubakiri.diaw\Anaconda3\lib\site-packages\tensorflow\python\frame

In [4]:
import keras

Using TensorFlow backend.


In [3]:

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Activation, Dense
from tensorflow.python.keras.optimizers import Adam
from tensorflow.python.keras.metrics import categorical_crossentropy

In [5]:
from tensorflow.keras.layers.experimental.preprocessing import Normalization

ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental.preprocessing'

In [86]:
train_labels=[]
train_samples=[]

In [87]:
for i in range(50):

    # the ~5% of younger individuals who did experience side effets
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    # the ~5% of older individuals who did not experience side effets
    random_older=randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)

for i in range(1000):

    # the ~95% of younger individuals who did not experience side effets
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    # the ~5% of older individuals who did experience side effets
    random_older=randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)
        
    



In [88]:
for i in train_samples:
    print(i)

38
94
37
82
43
93
15
76
23
73
34
76
24
77
31
79
24
100
48
99
25
89
29
92
59
100
48
91
40
95
26
69
63
84
35
81
63
80
25
93
17
70
39
71
31
100
34
95
24
67
57
76
55
68
63
66
16
100
61
96
47
98
43
81
13
93
42
75
57
94
47
98
44
82
35
94
42
90
52
75
18
70
25
77
55
91
44
99
35
94
58
83
39
83
27
87
50
89
25
65
35
67
32
75
51
92
24
84
13
75
16
97
62
71
38
81
60
77
29
67
63
91
14
94
31
68
62
71
58
81
17
98
37
79
22
76
18
97
19
79
20
86
38
76
42
67
14
100
42
71
26
85
15
93
15
78
63
85
53
99
15
95
29
71
51
79
54
91
46
81
25
85
49
77
51
66
46
85
56
78
54
82
38
68
31
68
27
100
41
92
21
83
53
93
61
94
57
74
52
80
52
92
49
87
53
66
64
66
39
75
39
87
29
100
37
82
41
98
62
87
40
90
36
77
13
69
25
87
63
100
20
67
30
83
25
84
20
86
62
65
36
92
18
67
55
82
61
91
57
92
47
98
29
66
27
89
54
81
49
76
27
91
64
83
23
97
64
80
33
93
26
67
26
87
47
82
50
82
52
71
22
83
26
68
62
88
55
95
37
98
53
90
56
84
37
76
60
85
24
73
25
66
15
81
15
89
54
78
60
93
34
85
64
70
33
70
56
99
20
92
62
76
27
89
27
95
62
79
20
94
25

In [89]:
for i in train_labels:
    print(i)

1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


In [90]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples) 
train_labels, train_samples= shuffle(train_labels, train_samples) 

In [91]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [92]:
for i in scaled_train_samples:
    print(i)

[0.59770115]
[0.95402299]
[0.86206897]
[0.90804598]
[0.95402299]
[0.29885057]
[0.52873563]
[0.65517241]
[0.56321839]
[0.25287356]
[0.73563218]
[0.2183908]
[0.8045977]
[0.52873563]
[0.33333333]
[0.17241379]
[0.26436782]
[0.13793103]
[0.40229885]
[0.91954023]
[0.42528736]
[0.03448276]
[0.86206897]
[0.11494253]
[0.18390805]
[0.88505747]
[0.24137931]
[0.8045977]
[0.20689655]
[0.04597701]
[0.96551724]
[0.71264368]
[0.74712644]
[0.10344828]
[0.35632184]
[0.]
[0.06896552]
[0.25287356]
[0.96551724]
[0.71264368]
[0.27586207]
[0.98850575]
[0.74712644]
[0.62068966]
[0.47126437]
[0.1954023]
[0.25287356]
[0.66666667]
[0.25287356]
[0.93103448]
[0.93103448]
[0.18390805]
[0.3908046]
[0.59770115]
[0.18390805]
[0.66666667]
[0.71264368]
[0.65517241]
[0.85057471]
[0.54022989]
[0.79310345]
[0.31034483]
[0.14942529]
[0.93103448]
[0.28735632]
[0.45977011]
[0.40229885]
[0.42528736]
[0.27586207]
[0.93103448]
[0.65517241]
[0.03448276]
[0.62068966]
[0.98850575]
[0.86206897]
[0.4137931]
[0.01149425]
[0.79310345]


[0.50574713]
[0.83908046]
[0.94252874]
[0.63218391]
[0.88505747]
[0.29885057]
[0.88505747]
[1.]
[0.67816092]
[0.70114943]
[0.94252874]
[0.02298851]
[0.7816092]
[0.56321839]
[0.94252874]
[0.95402299]
[0.73563218]
[0.63218391]
[0.59770115]
[0.71264368]
[0.09195402]
[0.72413793]
[0.47126437]
[0.98850575]
[0.94252874]
[0.91954023]
[0.68965517]
[0.10344828]
[0.8045977]
[0.03448276]
[0.91954023]
[0.94252874]
[0.71264368]
[0.96551724]
[0.22988506]
[0.36781609]
[0.1954023]
[0.55172414]
[0.09195402]
[0.05747126]
[0.52873563]
[0.90804598]
[0.83908046]
[0.32183908]
[0.71264368]
[0.45977011]
[0.54022989]
[0.31034483]
[0.90804598]
[0.96551724]
[0.1954023]
[0.43678161]
[0.27586207]
[0.28735632]
[0.91954023]
[0.45977011]
[0.16091954]
[0.64367816]
[0.90804598]
[0.94252874]
[0.66666667]
[0.2183908]
[0.82758621]
[0.33333333]
[0.7816092]
[0.88505747]
[0.11494253]
[0.73563218]
[0.71264368]
[0.32183908]
[0.29885057]
[0.98850575]
[0.72413793]
[0.06896552]
[0.27586207]
[0.71264368]
[0.5862069]
[0.09195402]
[

In [93]:
model = Sequential([
    Dense(units=16, input_shape=(1,), activation= 'relu' ),
    Dense(units=32, activation='relu'),
    Dense(units=2, activation='softmax')
])

In [94]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_7 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [95]:
model.compile(optimizer=Adam(lr=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy']) 

In [1]:
model.fit(x=scaled_train_samples, y=train_labels, validation_split=0.1, batch_size=10, epochs=50, shuffle=True, verbose=2)

NameError: name 'model' is not defined

## Preprocess Test Data

In [97]:
test_labels=[]
test_samples=[]

In [98]:
for i in range(10):

    # the ~5% of younger individuals who did experience side effets
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    # the ~5% of older individuals who did not experience side effets
    random_older=randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)

for i in range(200):

    # the ~95% of younger individuals who did not experience side effets
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    # the ~5% of older individuals who did experience side effets
    random_older=randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)
        

In [99]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples) 
test_labels, test_samples= shuffle(test_labels, test_samples) 

In [100]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

## Predict

In [42]:
predictions = model.predict(x=scaled_test_samples, batch_size=10, verbose=0)

In [43]:
for i in predictions:
    print(i)

[0.9709207 0.0290793]
[0.77954143 0.22045858]
[0.8951982  0.10480174]
[0.9704321  0.02956787]
[0.9114331  0.08856688]
[0.03884959 0.96115035]
[0.05220253 0.9477974 ]
[0.9711718  0.02882819]
[0.0184964 0.9815036]
[0.09949867 0.9005014 ]
[0.959886   0.04011399]
[0.12230945 0.87769055]
[0.9656622  0.03433786]
[0.08646996 0.91353   ]
[0.06495242 0.93504757]
[0.97055674 0.02944333]
[0.95628285 0.04371716]
[0.9706807  0.02931929]
[0.8686152  0.13138482]
[0.17327665 0.82672334]
[0.96993554 0.03006441]
[0.9706807  0.02931929]
[0.97153485 0.02846513]
[0.04850508 0.951495  ]
[0.95221233 0.04778766]
[0.02891809 0.971082  ]
[0.10664757 0.89335245]
[0.9709207 0.0290793]
[0.09277925 0.9072208 ]
[0.259448 0.740552]
[0.02492931 0.97507066]
[0.259448 0.740552]
[0.9645054  0.03549459]
[0.95221233 0.04778766]
[0.17327665 0.82672334]
[0.9706807  0.02931929]
[0.01716161 0.9828384 ]
[0.01993293 0.98006713]
[0.02147856 0.97852147]
[0.05616518 0.94383484]
[0.97165495 0.02834508]
[0.9714144  0.02858566]
[0.017

In [44]:
rounded_predictions = np.argmax(predictions, axis=-1)

In [45]:
for i in rounded_predictions:
    print(i)

0
0
0
0
0
1
1
0
1
1
0
1
0
1
1
0
0
0
0
1
0
0
0
1
0
1
1
0
1
1
1
1
0
0
1
0
1
1
1
1
0
0
1
1
1
1
0
0
0
1
0
0
0
1
1
1
0
0
1
0
1
0
1
1
0
0
0
1
0
1
1
0
1
0
1
0
1
0
0
1
0
0
0
1
1
0
1
1
1
1
0
0
0
0
0
0
0
1
0
1
0
0
1
1
0
0
1
1
1
0
1
0
1
0
0
1
1
0
0
1
0
1
1
1
0
1
1
0
1
1
1
1
1
1
1
0
0
1
1
1
0
1
1
0
1
0
0
0
1
0
1
0
1
0
0
0
0
0
0
1
0
0
0
1
0
0
0
1
0
0
1
0
0
0
0
1
1
0
1
0
1
0
1
1
1
0
1
0
1
1
0
0
1
0
1
0
0
1
1
0
0
0
0
0
0
1
1
0
0
1
1
0
0
0
0
1
0
0
1
1
0
1
1
1
0
1
0
1
1
0
1
1
0
0
0
1
0
1
0
1
1
1
1
0
1
0
1
1
0
1
0
0
0
1
0
1
0
0
1
1
0
0
1
0
1
1
1
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
1
1
0
1
1
1
1
1
1
1
1
0
1
1
0
0
1
0
1
0
0
1
0
1
0
0
1
1
0
1
1
1
0
1
1
1
0
0
0
1
1
1
0
0
1
0
1
0
1
0
1
0
1
0
0
0
1
1
1
0
0
0
1
1
1
0
1
0
0
0
1
1
1
0
0
1
0
1
1
1
0
1
0
0
1
1
0
1
1
1
1
1
0
0
0
0
1
0
0
1
0
1
1
1
1
0
1
1
0
1
0
1
0
0
1
1
1
1
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
0


In [47]:
%matplotlib inline
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [48]:
cm=confusion_matrix(y_true=test_labels, y_pred=rounded_predictions)

In [58]:
def plot_confusion_matrix(cm, classes, normalize=False, title='Confusion matrix', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)
    
    if normalize:
        cm= cm.astype('float')/cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('confusion matrix, without normalization')
    print(cm)
    
    thresh=cm.max()/2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j,i, cm[i,j], horizontalalignment="center", 
        color="white" if cm[i,j]> thresh else "black")
                 
                 
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [59]:
cm_plot_labels = ['no_side_effects', 'had_side_effects']
plot_confusion_matrix(cm=cm, classes=cm_plot_labels, title='confusion Matrix')

confusion matrix, without normalization
[[197  13]
 [  9 201]]


In [65]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


## Save and Load a Model

### 1.model.save()

In [64]:
#cheks first to see if file exists already
import os.path
if os.path.isfile('Desktop/keras/medical_trial_model.h5') is False:
    model.save('Desktop/keras/medical_trial_model.h5')

In [67]:
from tensorflow.python.keras.models import load_model
new_model = load_model('Desktop/keras/medical_trial_model.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [68]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [69]:
new_model.get_weights()

[array([[ 0.37057465,  0.6699438 , -0.48930156,  0.37481466,  0.27873945,
         -0.03403455,  0.10863264, -0.36539945, -0.57128775, -0.25059584,
          0.5312049 , -0.2624507 ,  0.68338096, -0.28481564,  0.3246326 ,
          0.66566503]], dtype=float32),
 array([-0.1874525 , -0.18690059,  0.        , -0.19084704,  0.22356792,
         0.        ,  0.22429731,  0.        ,  0.        ,  0.        ,
        -0.25350013,  0.        , -0.08147097,  0.        , -0.16480291,
        -0.2364639 ], dtype=float32),
 array([[-0.6475317 , -0.39441824, -0.15587236,  0.4703648 , -0.4062751 ,
          0.23740402, -0.05355922,  0.43227026, -0.7076132 ,  0.20366782,
         -0.72480357, -0.57161945,  0.6080814 , -0.08180977, -0.39414638,
         -0.44080693, -0.36425817, -0.39485493,  0.59289104,  0.17097062,
         -0.26035422,  0.42826268,  0.302685  , -0.17053011, -0.5659807 ,
          0.41887897, -0.26828676, -0.0423547 , -0.6612337 , -0.06988952,
         -0.07807057, -0.10937551],
 

In [70]:
new_model.optimizer

### 2.model.to_json()

Pour seulement enregistrer l'architecture du model

In [71]:
# save as JSON
json_string = model.to_json()
# save as yaml

In [72]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "Dense", "config": {"name": "dense", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null, "dtype": "float32"}}, "bias_initializer": {"class_name": "Zeros", "config": {"dtype": "float32"}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null, "dtype": "float32"}}, "bias_initializer": {"class_name": "Zeros", "config": {"dtype": "float32"}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null,

In [73]:
# reconstruction du modèle à partir de JSON
from tensorflow.python.keras.models import model_from_json
model_architecture = model_from_json(json_string)

In [75]:
model_architecture.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


### 3.model.save_weights()

Si tu veux seulement enregistrer les poids du modèle

In [76]:
#cheks first to see if file exists already
import os.path
if os.path.isfile('Desktop/keras/my_model_weights.h5') is False:
    model.save('Desktop/keras/my_model_weights.h5')

In [77]:
model2 = Sequential([
    Dense(units=16, input_shape=(1,), activation= 'relu' ),
    Dense(units=32, activation='relu'),
    Dense(units=2, activation='softmax')
])

In [78]:
model2.load_weights('Desktop/keras/my_model_weights.h5')

In [105]:
model2.get_weights()[0:3]

[array([[ 0.37057465,  0.6699438 , -0.48930156,  0.37481466,  0.27873945,
         -0.03403455,  0.10863264, -0.36539945, -0.57128775, -0.25059584,
          0.5312049 , -0.2624507 ,  0.68338096, -0.28481564,  0.3246326 ,
          0.66566503]], dtype=float32),
 array([-0.1874525 , -0.18690059,  0.        , -0.19084704,  0.22356792,
         0.        ,  0.22429731,  0.        ,  0.        ,  0.        ,
        -0.25350013,  0.        , -0.08147097,  0.        , -0.16480291,
        -0.2364639 ], dtype=float32),
 array([[-0.6475317 , -0.39441824, -0.15587236,  0.4703648 , -0.4062751 ,
          0.23740402, -0.05355922,  0.43227026, -0.7076132 ,  0.20366782,
         -0.72480357, -0.57161945,  0.6080814 , -0.08180977, -0.39414638,
         -0.44080693, -0.36425817, -0.39485493,  0.59289104,  0.17097062,
         -0.26035422,  0.42826268,  0.302685  , -0.17053011, -0.5659807 ,
          0.41887897, -0.26828676, -0.0423547 , -0.6612337 , -0.06988952,
         -0.07807057, -0.10937551],
 